Update README.md more info from docs
viamrobotics/viam-visual-odometry pull request #13
Opened 2023-12-05 20:49 UTC by sguequierre

Merging further into docs readme-- adding calibration info that was missing

2023-12-05 21:44 UTC, Rob1in commented on README.md
> +
This not completely accurate, [see here](https://github.com/viamrobotics/docs/pull/1691#discussion_r1320047180) and [here](https://github.com/viamrobotics/docs/pull/1691#pullrequestreview-1617788404) the changes

2023-12-06 16:37 UTC, npentrel requested changes

2023-12-06 16:37 UTC, npentrel commented on README.md
> +These calibration steps ensure that the video stream data that reaches the module is as uniform as possible when calculating measurements.
```suggestion
The following calibration steps ensure that the video stream data that reaches the module is as uniform as possible when calculating measurements.
```

2023-12-06 16:37 UTC, npentrel commented on README.md
Only the first sentence in the requirements section is a requirement. The rest should go into the introduction.

2023-12-06 16:37 UTC, npentrel commented on README.md
And line 2 can be improved with the intro content from the docs page:

```
A `monocular-visual-odometry` [modular resource](https://docs.viam.com/extend/modular-resources/) which uses monocular visual odometry to enable any calibrated camera to function as a movement sensor. In this way, you can add basic movement sensing to your camera-equipped robot without needing a dedicated hardware movement sensor.
```

2023-12-06 16:49 UTC, sguequierre commented on README.md
> +
Removing

2023-12-06 16:53 UTC, sguequierre commented on README.md
Done

2023-12-06 16:53 UTC, sguequierre commented on README.md
> +These calibration steps ensure that the video stream data that reaches the module is as uniform as possible when calculating measurements.
Done

2023-12-12 17:04 UTC, Rob1in approved these changes

2023-12-13 14:58 UTC, merged